export const LOADING_POKEMONS = 'LOADING_POKEMONS'
export const START_LOAD_POKEMONS = 'START_LOAD_POKEMONS'
export const SET_ALL_POKEMONS = 'SET_ALL_POKEMONS'

export const SET_ALL_TYPES = 'SET_ALL_TYPES'
export const SET_PROGRESS_BAR = 'SET_PROGRESS_BAR'

export const SHOW_POKEMON = 'SHOW_POKEMON'
export const HIDE_POKEMON = 'HIDE_POKEMON'

export const SET_PAGINATION = 'SET_PAGINATION'
export const UPDATE_NEXT_PAGINATION = 'UPDATE_NEXT_PAGINATION'

export const UPDATE_POKEMONS = 'UPDATE_POKEMONS'
export const ADD_POKEMONS = 'ADD_POKEMONS'

export const SET_PAGE_SIZE = 'SET_PAGE_SIZE'
export const SET_PAGE = 'SET_PAGE'